name: Deployment Pipeline
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build NextJS App
        run: yarn build
  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build artifacts
        run: yarn build
      - name: Configure AWS crendentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Sync pages to dev S3
        if: ${{ github.ref != 'refs/heads/main' }}
        run: aws s3 sync ./out s3://dev-szabi.space
      - name: Sync pages to prod S3
        if: ${{ github.ref == 'refs/heads/main' }}
        run: aws s3 sync ./out s3://szabi.space
      - run: echo "branchname is ${{ github.ref }}"
